### PR TITLE
fix: restrict access to elections

### LINKED ISSUE #290: add authorization to sensitive API calls
Ensure all API calls check action against user role and access scope.

- Creating an election
- Uploading a jurisdiction file

### PR DESCRIPTION
**Pull request by eventualbuddha**
**Description**

This puts the line to restrict access in each route that accesses an election by ID.

**Testing**

Covered by existing tests.

**Progress**

I believe this closes #290. However, it does so in a way that is fairly easy to forget to apply to a given route. We should open a new issue detailing a better way (edit: this is now https://github.com/votingworks/arlo/issues/335).

### CODE REVIEW

**Comment by eventualbuddha** [comment]
I could add tests for each endpoint. It might be a bit redundant, but perhaps worth it. The main question I have for @benadida and @MorganLove (and perhaps also @mcchilders) is this: do all of these endpoints require the logged-in user to be an audit admin?

**Comment by jonahkagan** [comment]
I'm currently trying to take baby steps towards having a set of tests for each endpoint anyway. Whenever I touch an endpoint I add a barebones test suite for it. Also see some new test helpers I'm adding in #336 that support that project

**Comment by mcchilders** [comment]
@eventualbuddha when you say "all of these endpoints" - can you define which ones? Or do you just mean literally any endpoint we've created? Not everything will require the user to be an AA, no, and we should prob be a little careful because some of these are likely getting reused between the single-page existing workflow (which we're keeping around for un-auth'd users) and the new multi-jurisdiction workflow ... don't want to inadvertently require it for something that's being used in both places?

**Comment by eventualbuddha** [comment]
> …some of these are likely getting reused between the single-page existing workflow (which we're keeping around for un-auth'd users) and the new multi-jurisdiction workflow ... don't want to inadvertently require it for something that's being used in both places?

That's a good point. Alright, sounds like we need to have more discussion around access permissions before we dig into this any more. Abandoning for now.

**Pull request closed without merging**
