### PR TITLE
Modify parse-xml-cvrs script to convert Hart CVRs to Dominion CVRs

### PR DESCRIPTION
**Pull request by jonahkagan**

### CODE REVIEW

**Review by umbernhard — APPROVED** [review]

**Comment by umbernhard** [comment]
@jonahkagan is there a reason this hasn't been merged?

**Comment by jonahkagan** [comment]
I started working on Hart CVR parsing in Arlo proper (not just as a script). So I was gonna just delete this script. But then that got blocked. I can close this PR for now - can always look at it later if needed.

**Comment by arsalansufi** [comment]
Script successfully run for Orange County! Details documented here: https://votingworks.slack.com/archives/C013V6CT9H9/p1655501678533819

**Comment by umbernhard** [comment]
Just for future consideration @carolinemodic @benadida, do we have any kind of guarantee that slack links will persist? I get that it's worked so far, and that it's maybe in Slacks business case to keep it like that, but couldn't they wake up tomorrow and obliterate the documentation here?

**Pull request merged**
