### PR TITLE
Standardize contest names

### PR DESCRIPTION
**Pull request by jonahkagan**
Task: #1007 

https://user-images.githubusercontent.com/530106/115788215-2d849a00-a378-11eb-80ac-8a88ef99efce.mov

### CODE REVIEW

**Comment by MorganLove** [comment]
@jonahkagan Looks awesome! A couple issues I ran into:

1) After the election is launched, the option to change the contest names still appears. I think this should be disabled because in between submitting the ballots, I changed the contest name and while signing off it showed an internal server error.

2) Added 3 jurisdictions. For 1st jurisdiction, used the ballot comparison file from the fixtures.

For 2nd & 3rd jurisdiction, used a CVR with different contest names - Contest 12 & Contest 21.

On the Launch page, from the dialog to choose correct names, I then chose the 1st option for just the first jurisdiction and saved.

Opened again, and chose another option for the second jurisdiction, and an internal error was shown. And after that, it didn't update the contest names and spinner kept loading on submission.

**Comment by jonahkagan** [comment]
Thanks @MorganLove. Addressed the first issue here: ab376aa9

**Comment by jonahkagan** [comment]
And fixed the second issue here: 753544a

**Review by MorganLove — APPROVED** [review]
Nice!

**Review by benadida — APPROVED** [review]

**Pull request merged**
