### PR TITLE
Remove providence from frontend per Oliver's concerns

### PR DESCRIPTION
**Pull request by combscCode**
Oliver raised some concerns about how we use random seeds for Providence. Until we can sort out a solution, we should disable Providence on the frontend.

### CODE REVIEW

**Comment by combscCode** [comment]
@arsalansufi could I get a review on this? Happy to forward context if you can send me your email.

**Review by arsalansufi — APPROVED** [review]
Hey @combscCode! Sorry for the delay here - LGTM!

**Comment by combscCode** [comment]
@arsalansufi I'll need you to merge the PR as well 😉 thanks!

**Comment by arsalansufi** [comment]
We don't have bandwidth at the moment @combscCode, but I've gone ahead and opened an issue so that we don't lose track of this! https://github.com/votingworks/arlo/issues/1812

If you have any additional context that you'd like to share, feel free to add to the issue. (I believe that you should be able to comment on it. If not, you can email me the details at arsalan@voting.works, and I can add them to the issue for you.)

Thanks again for bubbling this up to us!

**Pull request merged**
